{{- if .Values.secrets.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "my-stack.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
spec:
  backendType: {{ .Values.secrets.backendType }}
  dataFrom:
    - {{ $.Values.secrets.path }}
{{- end }}
